### PR TITLE
Various fixes for deprecated functions, adds Qt6 support

### PR DESCRIPTION
**Pull request by Herrie82**
Will now work with both Qt 5.15 and Qt 6.x.

Has not been tested on older versions of Qt 5.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by jmlich** [comment]
I have tried to recompile your branch on Manjaro as it seems commit 5c90061 resolves trouble with compilation caused by new gcc or new default compiler settings. In the end compilation failed with following error message:
```
jmlich@manajro-virt:~/workspace/libconnman-qt/build (herrie/qt6-clean =)$ qmake -r VERSION=1.2.43 ..
Info: creating stash file /home/jmlich/workspace/libconnman-qt/build/.qmake.stash
Reading /home/jmlich/workspace/libconnman-qt/libconnman-qt/libconnman-qt.pro [/home/jmlich/workspace/libconnman-qt/build/libconnman-qt]
WARNING: Failure to find: connman_vpn_manager_interface.h
WARNING: Failure to find: connman_vpn_connection_interface.h
Reading /home/jmlich/workspace/libconnman-qt/plugin/plugin.pro [/home/jmlich/workspace/libconnman-qt/build/plugin]
jmlich@manajro-virt:~/workspace/libconnman-qt/build (herrie/qt6-clean =)$ make
cd libconnman-qt/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/jmlich/workspace/libconnman-qt/libconnman-qt/libconnman-qt.pro VERSION=1.2.43 ) && make -f Makefile 
make[1]: Entering directory '/home/jmlich/workspace/libconnman-qt/build/libconnman-qt'
g++ -c -pipe -O2 -pthread -pthread -D_REENTRANT -flto -fno-fat-lto-objects -Wall -Wextra -fPIC -DHAVE_LIBDBUSACCESS=1 -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../libconnman-qt -I/home/jmlich/workspace/libconnman-qt/build/libconnman-qt -I/usr/include/dbusaccess -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gutil -I/usr/include/qt -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/home/jmlich/workspace/libconnman-qt/build/libconnman-qt -I/usr/lib/qt/mkspecs/linux-g++ -o marshalutils.o ../../libconnman-qt/marshalutils.cpp
In file included from /usr/include/qt/QtDBus/QDBusMetaType:1,
                 from ../../libconnman-qt/marshalutils.cpp:191:
/usr/include/qt/QtDBus/qdbusmetatype.h: In instantiation of ‘void qDBusMarshallHelper(QDBusArgument&, const T*) [with T = RouteStructure]’:
/usr/include/qt/QtDBus/qdbusmetatype.h:81:12:   required from ‘int qDBusRegisterMetaType(T*) [with T = RouteStructure]’
../../libconnman-qt/marshalutils.cpp:195:42:   required from here
/usr/include/qt/QtDBus/qdbusmetatype.h:68:7: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDBusArgument’ and ‘const RouteStructure’)
   68 | { arg << *t; }
      |   ~~~~^~~~~
../../libconnman-qt/marshalutils.cpp:41:30: note: candidate: ‘QDBusArgument& operator<<(QDBusArgument&, const RouteStructure&)’
   41 | Q_DBUS_EXPORT QDBusArgument &operator<<(QDBusArgument &a, const RouteStructure &v);
      |                              ^~~~~~~~
../../libconnman-qt/marshalutils.cpp:48:16: note: candidate: ‘QDBusArgument& {anonymous}::operator<<(QDBusArgument&, const RouteStructure&)’
   48 | QDBusArgument &operator<<(QDBusArgument &argument, const RouteStructure &routestruct)
      |                ^~~~~~~~
/usr/include/qt/QtDBus/qdbusmetatype.h: In instantiation of ‘void qDBusDemarshallHelper(const QDBusArgument&, T*) [with T = RouteStructure]’:
/usr/include/qt/QtDBus/qdbusmetatype.h:82:12:   required from ‘int qDBusRegisterMetaType(T*) [with T = RouteStructure]’
../../libconnman-qt/marshalutils.cpp:195:42:   required from here
/usr/include/qt/QtDBus/qdbusmetatype.h:72:7: error: ambiguous overload for ‘operator>>’ (operand types are ‘const QDBusArgument’ and ‘RouteStructure’)
   72 | { arg >> *t; }
      |   ~~~~^~~~~
../../libconnman-qt/marshalutils.cpp:40:36: note: candidate: ‘const QDBusArgument& operator>>(const QDBusArgument&, RouteStructure&)’
   40 | Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, RouteStructure &v);
      |                                    ^~~~~~~~
../../libconnman-qt/marshalutils.cpp:63:22: note: candidate: ‘const QDBusArgument& {anonymous}::operator>>(const QDBusArgument&, RouteStructure&)’
   63 | const QDBusArgument &operator>>(const QDBusArgument &argument, RouteStructure &routestruct)
      |                      ^~~~~~~~
../../libconnman-qt/marshalutils.cpp:63:22: warning: ‘const QDBusArgument& {anonymous}::operator>>(const QDBusArgument&, RouteStructure&)’ defined but not used [-Wunused-function]
../../libconnman-qt/marshalutils.cpp:48:16: warning: ‘QDBusArgument& {anonymous}::operator<<(QDBusArgument&, const RouteStructure&)’ defined but not used [-Wunused-function]
   48 | QDBusArgument &operator<<(QDBusArgument &argument, const RouteStructure &routestruct)
      |                ^~~~~~~~
make[1]: *** [Makefile:1051: marshalutils.o] Error 1
make[1]: Leaving directory '/home/jmlich/workspace/libconnman-qt/build/libconnman-qt'
make: *** [Makefile:48: lib-target-make_first] Error 2
```

```
jmlich@manajro-virt:~/workspace/libconnman-qt (herrie/qt6-clean %=)$ gcc --version
gcc (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jmlich@manajro-virt:~/workspace/libconnman-qt (herrie/qt6-clean %=)$ qmake-qt5 --version
QMake version 3.1
Using Qt version 5.15.4 in /usr/lib
```

**Comment by Tofee** [comment]
@jmlich Unfortunately I didn't fully understand the actual origin of this error, as just including the header shouldn't trigger errors related to the templates declared later on in the cpp... Out of spite I tried just moving the include a bit later in the cpp, before we actually use what's declared in the header. That worked well with Qt 6, Qt 5.15, compiled with gcc 11. It could be the issue is still unsolved for gcc 12.

**Comment by Herrie82** [comment]
@jmlich I guess something like this one might work? https://github.com/sailfishos/libconnman-qt/pull/9/commits/9be6c1838b17247a9a1400805fdf3036e3f0b8e8

**Comment by Herrie82** [comment]
@Thaodan This replaces the other PR, I've cut it up into separate commits with more documentation now

File: libconnman-qt/counter.cpp [hunk 1]
```diff
@@ -8,6 +8,7 @@
  */
 
 #include <QtDBus/QDBusConnection>
+#include <QRandomGenerator>
```
Comment (monich) [inline libconnman-qt/counter.cpp:12]:
```
[   60s] counter.cpp:11:10: fatal error: QRandomGenerator: No such file or directory
[   60s]  #include <QRandomGenerator>
[   60s]           ^~~~~~~~~~~~~~~~~~
[   60s] compilation terminated.
[   60s] make[1]: *** [Makefile:607: counter.o] Error 1
```
Qt 5.6

Comment (Herrie82) [reply libconnman-qt/counter.cpp:12]: Seems QRandomGenerator was added in 5.10

You happy with checking Qt version here and including the header accordingly or you propose a differrent solution?

Comment (monich) [reply libconnman-qt/counter.cpp:12]: Not being a maintainer of this thing, I guess it's whatever as long as it still compiles against Qt 5.6 (which is currently a requirement for Sailfish OS)

Comment (Tofee) [reply libconnman-qt/counter.cpp:12]: I can do a conditional code, depending on old/new Qt version. It should be pretty straightforward.

Comment (Herrie82) [reply libconnman-qt/counter.cpp:12]: @monich Pushed a fix that should allow it to compile on Qt < 5.10 :)

File: libconnman-qt/clockmodel.cpp [hunk 2]
```diff
@@ -154,13 +154,13 @@ void ClockModel::setTimeservers(const QStringList &val)
 void ClockModel::setDate(QDate date)
 {
     QDateTime toDate(date, QTime::currentTime());
-    quint64 secsSinceEpoch = (quint64)toDate.toTime_t();
```
Comment (pvuorela) [inline libconnman-qt/clockmodel.cpp:157]: toMSecsSinceEpoch() / 1000 would be compatible with older qt.

Wonder if the qint64 / quint64 difference between the types matter. Anyhow don't think this class is effectively used in sailfish. For side-note not sure should it even exist in connman api.

Comment (Herrie82) [reply libconnman-qt/clockmodel.cpp:157]: @tofee any thoughts?

Comment (Tofee) [reply libconnman-qt/clockmodel.cpp:157]: We can completely use "toMSecsSinceEpoch() / 1000" instead, I didn't realize the other API was a recent one.
For qint64 I guess the difference is mainly about pre-Epoch dates, where you would get negative numbers.

Comment (Herrie82) [reply libconnman-qt/clockmodel.cpp:157]: Just pushed it via: https://github.com/sailfishos/libconnman-qt/pull/9/commits/5361c003e72ae90a59c08fd4c5dfe1987fbf6241

Time seems to be uint64 as per https://github.com/aldebaran/connman/blob/master/doc/clock-api.txt#L31

**Comment by Herrie82** [comment]
@jmlich @pvuorela @monich @rainemak Any further comments on this one?

**Comment by jmlich** [comment]
The suggested approach/commit didn't helped. My issue is not directly related to this pull request. I don't want to hijack it. (-;
The changes looks good to me. I have tried to recompile it just with Qt5 with result described above.

File: libconnman-qt/marshalutils.cpp [hunk 3]
```diff
@@ -31,11 +31,16 @@
...
 #include <QDebug>
-#include <QDBusMetaType>
+#include <QDBusArgument> 
 #include "vpnconnection.h"
 
 #include "marshalutils.h"
 
+#if defined(__clang__) &&  __clang_major__ >= 11 || __GNUC__ >= 12
+Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, RouteStructure &v);
+Q_DBUS_EXPORT QDBusArgument &operator<<(QDBusArgument &a, const RouteStructure &v);
```
Comment (pvuorela) [inline libconnman-qt/marshalutils.cpp]: This looks strange to me in may ways.  First the Q_DBUS_EXPORT not being a documented, looks like it should end up as Q_DECL_IMPORT/EXPORT. Then again the symbol visibilities shouldn't generally depend on compiler. And then again generally the visibilities should only matter on something using this from a shared library. And not sure does the library here get even compiled with hidden symbols by default. There are no Q_DECL_... usage elsewhere so I'm guessing no. And finally this is exporting something from the anon namespace which by definition should be internal to the file.

I'm having a feeling this might be fixing something by accident.

**Comment by pvuorela** [comment]
Beside that dbus export this looks good. Ideally could squash the commits which adjust the same code based on review comments, though.

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (Tofee) [reply libconnman-qt/marshalutils.cpp]: It could be that Q_DBUS_EXPORT is just useless here, I didn't really check that

**Comment by Herrie82** [comment]
> Q_DBUS_EXPORT

I squashed those. The Q_DBUS_EXPORT I cherry-picked from meta-qt5 layer and included it in this PR, so I'm just the messenger here. @kraj is the author of the [original patch](https://github.com/meta-qt5/meta-qt5/commit/23f78f70d9aedddd09b581854368ab2af9f46b8c), so he might have more background on it.

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (pvuorela) [reply libconnman-qt/marshalutils.cpp]: Perhaps, but even without that this would be having different declaration for content inside the anon namespace. 

There was a small compiler error snippet in the commit message. Would you have the bigger error message available in case it helps figuring out what's the problem.

File: libconnman-qt/vpnmodel.h [hunk 4]
```diff
@@ -34,9 +34,9 @@
 #define VPNMODEL_H
 
 #include <QAbstractListModel>
+#include "vpnmanager.h"
 
 class VpnModelPrivate;
-class VpnManager;
```
Comment (rainemak) [inline libconnman-qt/vpnmodel.h:39]: This looks fishy as there are only pointers in the header. There seems to be system include of the vpnmanager in the cpp file. Maybe source should look like:

```
#include <QtDBus>

#include "vpnconnection.h"
#include "vpnmodel.h"
#include "vpnmodel_p.h"

#include "vpnmanager.h"
#include "vpnmanager_p.h"
```

In case you happen to have connman-qt5-devel installed the at same time, wrong might get picked up.

That would mean that vpnmodel.h would have "class VpnManager;" forward declaration in place.

File: libconnman-qt/vpnmanager.h [hunk 5]
```diff
@@ -34,10 +34,10 @@
 #define VPNMANAGER_H
 
 #include <QObject>
+#include "vpnconnection.h"
 
 class VpnManagerPrivate;
 class VpnManager;
-class VpnConnection;
```
Comment (rainemak) [inline libconnman-qt/vpnmanager.h:40]: Same here. Move `"vpnconnection.h"` include  to the source file and keep `class VpnConnection;` forward declaration in place.

**Review by rainemak — COMMENTED** [review]
Added comments regarding forward declaration.

File: libconnman-qt/vpnmodel.h (hunk 4 above)
Comment (Tofee) [reply libconnman-qt/vpnmodel.h:39]: There is a QML property that uses this type, and therefore it isn't possible anymore in Qt6 to forward-declare the associated type.
There are two ways to fix this:
* as it has been done here, with a simple include
* using the Q_MOC_INCLUDE macro, to include it during moc processing

See: https://doc.qt.io/qt-6/qtcore-changes-qt6.html#type-registration

Comment (Herrie82) [reply libconnman-qt/vpnmodel.h:39]: @rainemak Happy to try it with Q_MOC_INCLUDE if that's more to your liking and adjust accordingly

Comment (Herrie82) [reply libconnman-qt/vpnmodel.h:39]: @rainemak: Tested with Q_MOC_INCLUDE that seems fine as well, so pushed that instead and squashed the commits.

Comment (pvuorela) [reply libconnman-qt/vpnmodel.h:39]: Q_MOC_INCLUDE was introduced in qt 6.0 so a common #include should be cleaner here, avoiding version specific handling.

Comment (Herrie82) [reply libconnman-qt/vpnmodel.h:39]: > Q_MOC_INCLUDE was introduced in qt 6.0 so a common #include should be cleaner here, avoiding version specific handling.

I can change it back if both @pvuorela @rainemak are happy with that approach

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (Herrie82) [reply libconnman-qt/marshalutils.cpp]: > Perhaps, but even without that this would be having different declaration for content inside the anon namespace.
> 
> There was a small compiler error snippet in the commit message. Would you have the bigger error message available in case it helps figuring out what's the problem.

Here's a full log: http://errors.yoctoproject.org/Errors/Details/655056/

Comment (Herrie82) [reply libconnman-qt/marshalutils.cpp]: @pvuorela And another one: https://pastebin.ubuntu.com/p/D5RRy77K8v/

Comment (Herrie82) [reply libconnman-qt/marshalutils.cpp]: @pvuorela Any thoughts based on above logs? I got a build system with GCC 12 here to test if needed.

File: libconnman-qt/vpnmodel.h (hunk 4 above)
Comment (pvuorela) [reply libconnman-qt/vpnmodel.h:39]: Even if used, it would need to be protected with qt version #ifdef and something else provided for Qt5. I wouldn't expect Raine either favoring such. Just about the first time we are adding Qt6 support so the forward declaration vs #include on Q_PROPERTIES wasn't a self-evident change.

Comment (Herrie82) [reply libconnman-qt/vpnmodel.h:39]: @pvuorela @rainemak Made the Q_MOC_INCLUDE only for Qt 6 with https://github.com/sailfishos/libconnman-qt/pull/9/commits/b20683f2646a60406b03788989e605f1c31ee98f That should work in both 5.x and 6.x versions.

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (pvuorela) [reply libconnman-qt/marshalutils.cpp]: Thanks. Tested also local build with qt6 and the current version here didn't work.

But tried a minor adjustment which could make more sense. Suggest:
- remove this export thing
- move the empty namespace declaration two methods downwards so the dbus argument operators are not inside it.

File: libconnman-qt/marshalutils.cpp [hunk 6]
```diff
@@ -183,6 +188,7 @@ QVariantMap MarshalUtils::propertiesToQml(const QVariantMap &fromDBus)
     return rv;
 }
 
+#include <QDBusMetaType>
```
Comment (pvuorela) [inline libconnman-qt/marshalutils.cpp]: Includes to the beginning of the file.

File: libconnman-qt/vpnmodel.h (hunk 4 above)
Comment (pvuorela) [reply libconnman-qt/vpnmodel.h:39]: Should be good enough too. But maybe on next one just do the basic #include.

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (Herrie82) [reply libconnman-qt/marshalutils.cpp]: > Thanks. Tested also local build with qt6 and the current version here didn't work.
> 
> But tried a minor adjustment which could make more sense. Suggest:
> 
> * remove this export thing
> * move the empty namespace declaration two methods downwards so the dbus argument operators are not inside it.

Sorry I'm not that great when it comes to C(++) ;)
You mean like this? https://github.com/webOS-ports/libconnman-qt/commit/eb38903048e90d6d7b9c323ad131ff8c3bbd7c31

BTW: This was tested with GCC 11/12.1 and Qt5.15/6.3 and compiling here without issues.

File: libconnman-qt/vpnmodel.h (hunk 4 above)
Comment (Herrie82) [reply libconnman-qt/vpnmodel.h:39]: > Should be good enough too. But maybe on next one just do the basic #include.

Which next one?

Comment (pvuorela) [reply libconnman-qt/vpnmodel.h:39]: Meaning if you do another similar pull request on another project.

File: libconnman-qt/marshalutils.cpp (hunk 3 above)
Comment (pvuorela) [reply libconnman-qt/marshalutils.cpp]: Same effect, yes. The pre-declarations are unnecessary there, though, when the implementations come right after them.

Comment (Herrie82) [reply libconnman-qt/marshalutils.cpp]: > Same effect, yes. The pre-declarations are unnecessary there, though, when the implementations come right after them.

OK removed those as well and cleaned up the commits into a single one.

**Comment by Herrie82** [comment]
> I have tried to recompile your branch on Manjaro as it seems commit [5c90061](https://github.com/sailfishos/libconnman-qt/commit/5c900611a573ac61f7a7cb3e886a054f6e0585fd) resolves trouble with compilation caused by new gcc or new default compiler settings. In the end compilation failed with following error message:
> 
> ```
> jmlich@manajro-virt:~/workspace/libconnman-qt/build (herrie/qt6-clean =)$ qmake -r VERSION=1.2.43 ..
> Info: creating stash file /home/jmlich/workspace/libconnman-qt/build/.qmake.stash
> Reading /home/jmlich/workspace/libconnman-qt/libconnman-qt/libconnman-qt.pro [/home/jmlich/workspace/libconnman-qt/build/libconnman-qt]
> WARNING: Failure to find: connman_vpn_manager_interface.h
> WARNING: Failure to find: connman_vpn_connection_interface.h
> Reading /home/jmlich/workspace/libconnman-qt/plugin/plugin.pro [/home/jmlich/workspace/libconnman-qt/build/plugin]
> jmlich@manajro-virt:~/workspace/libconnman-qt/build (herrie/qt6-clean =)$ make
> cd libconnman-qt/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/jmlich/workspace/libconnman-qt/libconnman-qt/libconnman-qt.pro VERSION=1.2.43 ) && make -f Makefile 
> make[1]: Entering directory '/home/jmlich/workspace/libconnman-qt/build/libconnman-qt'
> g++ -c -pipe -O2 -pthread -pthread -D_REENTRANT -flto -fno-fat-lto-objects -Wall -Wextra -fPIC -DHAVE_LIBDBUSACCESS=1 -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../libconnman-qt -I/home/jmlich/workspace/libconnman-qt/build/libconnman-qt -I/usr/include/dbusaccess -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gutil -I/usr/include/qt -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/home/jmlich/workspace/libconnman-qt/build/libconnman-qt -I/usr/lib/qt/mkspecs/linux-g++ -o marshalutils.o ../../libconnman-qt/marshalutils.cpp
> In file included from /usr/include/qt/QtDBus/QDBusMetaType:1,
>                  from ../../libconnman-qt/marshalutils.cpp:191:
> /usr/include/qt/QtDBus/qdbusmetatype.h: In instantiation of ‘void qDBusMarshallHelper(QDBusArgument&, const T*) [with T = RouteStructure]’:
> /usr/include/qt/QtDBus/qdbusmetatype.h:81:12:   required from ‘int qDBusRegisterMetaType(T*) [with T = RouteStructure]’
> ../../libconnman-qt/marshalutils.cpp:195:42:   required from here
> /usr/include/qt/QtDBus/qdbusmetatype.h:68:7: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDBusArgument’ and ‘const RouteStructure’)
>    68 | { arg << *t; }
>       |   ~~~~^~~~~
> ../../libconnman-qt/marshalutils.cpp:41:30: note: candidate: ‘QDBusArgument& operator<<(QDBusArgument&, const RouteStructure&)’
>    41 | Q_DBUS_EXPORT QDBusArgument &operator<<(QDBusArgument &a, const RouteStructure &v);
>       |                              ^~~~~~~~
> ../../libconnman-qt/marshalutils.cpp:48:16: note: candidate: ‘QDBusArgument& {anonymous}::operator<<(QDBusArgument&, const RouteStructure&)’
>    48 | QDBusArgument &operator<<(QDBusArgument &argument, const RouteStructure &routestruct)
>       |                ^~~~~~~~
> /usr/include/qt/QtDBus/qdbusmetatype.h: In instantiation of ‘void qDBusDemarshallHelper(const QDBusArgument&, T*) [with T = RouteStructure]’:
> /usr/include/qt/QtDBus/qdbusmetatype.h:82:12:   required from ‘int qDBusRegisterMetaType(T*) [with T = RouteStructure]’
> ../../libconnman-qt/marshalutils.cpp:195:42:   required from here
> /usr/include/qt/QtDBus/qdbusmetatype.h:72:7: error: ambiguous overload for ‘operator>>’ (operand types are ‘const QDBusArgument’ and ‘RouteStructure’)
>    72 | { arg >> *t; }
>       |   ~~~~^~~~~
> ../../libconnman-qt/marshalutils.cpp:40:36: note: candidate: ‘const QDBusArgument& operator>>(const QDBusArgument&, RouteStructure&)’
>    40 | Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, RouteStructure &v);
>       |                                    ^~~~~~~~
> ../../libconnman-qt/marshalutils.cpp:63:22: note: candidate: ‘const QDBusArgument& {anonymous}::operator>>(const QDBusArgument&, RouteStructure&)’
>    63 | const QDBusArgument &operator>>(const QDBusArgument &argument, RouteStructure &routestruct)
>       |                      ^~~~~~~~
> ../../libconnman-qt/marshalutils.cpp:63:22: warning: ‘const QDBusArgument& {anonymous}::operator>>(const QDBusArgument&, RouteStructure&)’ defined but not used [-Wunused-function]
> ../../libconnman-qt/marshalutils.cpp:48:16: warning: ‘QDBusArgument& {anonymous}::operator<<(QDBusArgument&, const RouteStructure&)’ defined but not used [-Wunused-function]
>    48 | QDBusArgument &operator<<(QDBusArgument &argument, const RouteStructure &routestruct)
>       |                ^~~~~~~~
> make[1]: *** [Makefile:1051: marshalutils.o] Error 1
> make[1]: Leaving directory '/home/jmlich/workspace/libconnman-qt/build/libconnman-qt'
> make: *** [Makefile:48: lib-target-make_first] Error 2
> ```
> 
> ```
> jmlich@manajro-virt:~/workspace/libconnman-qt (herrie/qt6-clean %=)$ gcc --version
> gcc (GCC) 12.1.0
> Copyright (C) 2022 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> jmlich@manajro-virt:~/workspace/libconnman-qt (herrie/qt6-clean %=)$ qmake-qt5 --version
> QMake version 3.1
> Using Qt version 5.15.4 in /usr/lib
> ```

@jmlich This works for me with GCC 12.1:
https://github.com/sailfishos/libconnman-qt/pull/9/commits/a1c462ebd38a5628aba20b30baa76a79fd8bdf6a

**Comment by jmlich** [comment]
I can confirm, that current version works for me.

**Comment by Herrie82** [comment]
> I can confirm, that current version works for me.

Great, thanks for testing and confirming!

**Review by pvuorela — APPROVED** [review]
Is good.

**Comment by shr-project** [comment]
This is now tagged as 1.2.46, but the version in .pro and .spec file is still 1.2.35 as set in https://github.com/sailfishos/libconnman-qt/commit/347f20fe1a03bf0624f55b9108c797611e79f7d2 should it be bumped to match the git tag?

**Comment by pvuorela** [comment]
Sailfish picks the version from the tag, .spec is commonly kept roughly in sync e.g. to help local builds but commonly does not matter too much if it lags a bit. The .pro file could have effect on other distributions as it affects the .so naming but wouldn't expect even that to matter too much.
